<?php

/**
 * @file
 * Contains bookmarks.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bookmarks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bookmarks module.
    case 'help.page.bookmarks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allowed bookmarks entity for administrate easiest by users.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_preprocess_node function.
 */
function bookmarks_preprocess_node(&$variables) {

  $variables["#attached"]["library"][] = "bookmarks/bookmarks";

}
